### ISSUE TITLE
use routing-controllers

### ISSUE THREAD

**Issue by pleerock** [ubiquits/ubiquits#106]
I have immodest question - why not to use [routing-controllers](https://github.com/pleerock/routing-controllers)? I think it have all features you need...

**Comment by zakhenry** [comment]
Yea I like what you've done with routing-controllers, however due to architecture decisions with how the ubiquits framework is bootstrapped, there would have to be a huge amount of coercing routing-controllers to work how I require. 

Besides, I've implemented most (all?) of the features routing-controllers offers already and 100% unit tested

**Comment by pleerock** [comment]
😞
